version = 0.1
[default.deploy.parameters]
stack_name = "PIApi"
resolve_s3 = true
s3_prefix = "PIApi"
region = "us-east-2"
profile = "tzdev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
